# Generated by Django 4.2.9 on 2024-03-23 19:24
from django.db import migrations, models
from datetime import datetime
from django.utils import timezone


def add_users(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    Employer = apps.get_model("users", "Employer")
    Recruiter = apps.get_model("users", "Recruiter")

    tz = timezone.get_current_timezone()
    now_datetime = datetime.now().replace(tzinfo=tz)

    CustomUser(
        id=1,
        created_at=now_datetime,
        username='admin',
        first_name='Admin',
        last_name='Adminskiy',
        password='111111',
        role='employer',
        is_superuser=True
    ).save()
    CustomUser(
        id=2,
        created_at=now_datetime,
        username='vasya',
        first_name='Василий',
        last_name='Пупкин',
        password='zxc102938',
        role='employer',
        is_superuser=False
    ).save()
    CustomUser(
        id=3,
        created_at=now_datetime,
        username='joe',
        first_name='Джо',
        last_name='Блэк',
        password='mko091122',
        role='recruiter',
        is_superuser=False
    ).save()
    Employer(
        company='Маленькая компания',
        position='директор',
        user_id=2,
    ).save()
    Employer(
        company='Большая компания',
        position='менеджер',
        user_id=3,
    ).save()
    Recruiter(
        about_me='Мастер на все руки',
        top10=True,
        finished_cases=10,
        years_of_exp=10,
        user_id=2,
    ).save()
    Recruiter(
        about_me='Я не волшебник, я только учусь',
        top10=False,
        finished_cases=1,
        years_of_exp=1,
        user_id=3,
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_users),
    ]
