# Generated by Django 4.2.9 on 2024-03-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidcountry',
            options={'verbose_name': 'Связь заявки и разрешенной страны гражданства', 'verbose_name_plural': 'Связи заявки и разрешенной страны гражданства'},
        ),
        migrations.AlterModelOptions(
            name='bidemployeeaddskill',
            options={'verbose_name': 'Связь заявки и доп. навыка соискателя', 'verbose_name_plural': 'Связи заявки и доп. навыка соискателя'},
        ),
        migrations.AlterModelOptions(
            name='bidemployeecategory',
            options={'verbose_name': 'Связь заявки и разрешенной страны гражданства', 'verbose_name_plural': 'Связи заявки и разрешенной страны гражданства'},
        ),
        migrations.RemoveField(
            model_name='bid',
            name='work_format',
        ),
        migrations.CreateModel(
            name='BidWorkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.bid', verbose_name='ID заявки')),
                ('work_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.workformat', verbose_name='ID формата работы')),
            ],
            options={
                'verbose_name': 'Связь заявки и формата работы',
                'verbose_name_plural': 'Связи заявки и формата работы',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='work_formats',
            field=models.ManyToManyField(through='bids.BidWorkFormat', to='bids.workformat', verbose_name='Форматы работы'),
        ),
        migrations.AddConstraint(
            model_name='bidworkformat',
            constraint=models.UniqueConstraint(fields=('bid', 'work_format'), name='bid_work_format'),
        ),
    ]
