# Generated by Django 4.2.9 on 2024-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_bidcountry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffoption',
            name='description',
            field=models.CharField(default=0, max_length=250, verbose_name='Описание тарифа'),
            preserve_default=False,
        ),
    ]
