# Generated by Django 4.2.9 on 2024-03-25 12:35

from django.db import migrations


def add_data(apps, schema_editor):
    TariffOption = apps.get_model("bids", "TariffOption")
    data = [
        {'name': '100% за выход сотрудника',
         'payment_for_employee_start_working': 100,
         'payment_for_employee_after_guarantee': 0,
         'guarantee_period': 0,
         'units_of_measurement_warranty_period': 'day',
         'description': 'Отличный вариант, чтобы на заявку откликнулись «звездные» рекрутеры с опытом.',
         },
        {'name': '50% - после выхода, 50% - после гарантийного периода',
         'payment_for_employee_start_working': 50,
         'payment_for_employee_after_guarantee': 50,
         'guarantee_period': 1,
         'units_of_measurement_warranty_period': 'month',
         'description': 'Гарантийный период — испытательный срок. 1 месяц после выхода сотрудника.',
         },
        {'name': '100% - после гарантийного периода',
         'payment_for_employee_start_working': 0,
         'payment_for_employee_after_guarantee': 100,
         'guarantee_period': 1,
         'units_of_measurement_warranty_period': 'month',
         'description': 'Это 1 месяц после выхода сотрудника. Доступен выбор одного рекрутера.',
         },
    ]
    for row in data:
        TariffOption.objects.update_or_create(**row)

    RecruiterTask = apps.get_model("bids", "RecruiterTask")
    data = [
        {'name': 'Поиск и предоставление релевантных резюме'},
        {'name': 'Организация собеседований с заказчиком, синхронизация по времени соискателя и заказчика'},
        {'name': 'Запрос рекомендаций с предыдущих мест работы'},
        {'name': 'Отправка кандидату тестового задания'},
        {'name': 'Отправка кандидату анкеты службы безопасности вашей компании'},
        {'name': 'Отправка финалисту приглашения на работу'},
    ]
    for row in data:
        RecruiterTask.objects.update_or_create(**row)

class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_remove_bidemployeeaddskill_bid_and_more'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
